### ISSUE TITLE
Make a quick Tutorial

### ISSUE THREAD

**Issue by salvacorts** [fidele007/Asus-ROG-GL552VW-Hackintosh#1]
I have the same pc and I would love to hackintosh it. May u pless add a quick tutorial?

Thanks!

**Comment by ghost** [comment]
me too, i cant make the usb to boot and i dont know how..

**Comment by fsdevocean** [comment]
Please make a full tutorial on it. It will be helpful for novices like me

**Comment by fidele007** [comment]
The first guide is out for [Mojave](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/tree/mojave)
