### ISSUE TITLE
failed during installation

### ISSUE THREAD

**Issue by Qunqun64** [fidele007/Asus-ROG-GL552VW-Hackintosh#11]
Hello.

Pardon my language, I am French and I do not speak English very well 😉
I tried the installation via this thread, clover works pretty well, but during the launch, I cant get to the installer: after a while, the installation hangs and asks to contact the Apple service to solve the problem.
I saw that it could be caused by the file lilu.kext, indeed it is the version 1.2.7 which is given in the downloads, but the last release is 1.3.5.
But that does not solve the problem.

Did you have this problem too? how did you solve it?

Thank you in advance !

P.S. I have a rog gl552vw ...

**Comment by agravelot** [comment]
Hello,

I'm facing the same kind of issue with my GL552VX.
Try to remove the `DSDT.aml` file from `CLOVER/ACPI/patched`.

But I can not make my backlight, battery level, touchpad and mic working.
I have checked the XHC, they are the same.

**Comment by Qunqun64** [comment]
Thanks for your quikly answer.
I try it, but it doesn't work. There is still the error message.
You can see this in attachment.
![20190405_185416](https://user-images.githubusercontent.com/49106283/55644638-d2a29900-57d6-11e9-9c01-7a0e3c5ef233.jpg)
![20190405_185427](https://user-images.githubusercontent.com/49106283/55644664-e3530f00-57d6-11e9-9f39-60afcf82b109.jpg)

**Comment by andreimerfu** [comment]
Hello 
I have the same problem with @Qunqun64.

**Comment by Qunqun64** [comment]
Hi.

I did not solve the problem, but still managed to get to the installer:
Fidele007 did a good job, (thank), and I didn’t follow it correctly: it was enough to take the file config_preinstall.plist and rename it in config.plist, and remove the already present. It has all the presets for it to work alone.

So, I finally arrived at the installer, still adding the file IntelGraphicsFixup.kext, because I had a black screen that prevented the installation, but now I have the MacOs Mojave launcher.
I still have a problem of partition: my disk can’t format itself in MacOs journalized, if I want to keep my Windows partition in ntfs. This prevents me from installing so, but this is only a minor problem.
If you have any ideas, otherwise I'm doing a backup to format the entire disk, and partition it afterwards to recover my files.

I hope it can help some, and thank you for your answers!

**Comment by andreimerfu** [comment]
@Qunqun64 you followed the guide or just copy-paste the clover directory to the EFI partition and then rename config.plist ?

**Comment by Qunqun64** [comment]
I followed the guide for formatting the key, and to install the Mojave application.
Then I followed the guide for the installation of Clover, and its configuration, because that's how the efi partition is created.

After I downloaded the folder, and copy-paste to replace the efi folder. be careful to put the files in the right folder, not too early! and nothing more. just the graphics driver, and that's it.

But it's not over, the installation is not finished, there may be problems.

**Comment by Qunqun64** [comment]
Hello.

How did your installation work @andreimerfu?
I arrived at the installer, but I still have a problem, saying that my download is not complete or valid, and that it is necessary to reload loading macos Mojave ...
A recurring problem from what I saw on the internet, but I have not managed to solve it yet.  I tried to change vm, change network provider for download, but nothing to do, always the same message.

If you have information or suggestions?
Did you have this same problem?

I have, as mentioned above, followed the entire tutorial, by downloading myself the .kexts, to be as up to date as possible, and taking the file config_preinstall.plist @fidele007 to rename it in config.plist,  which allowed me to enter the installer correctly, but I am stuck here.

Thank you in advance for the ideas you will have!

**Comment by andreimerfu** [comment]
Hello @Qunqun64

No, the installation didn't work.  Can you upload your Clover files, please?
I tried your instructions but still not working.

Thank you.

**Comment by Qunqun64** [comment]
my efi files, with all files, clover and boot.
if it work for you, can you explain my what is your instructions ?
perhaps my fault is to use a VM for the download...

let me know,

[EFI.zip](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/files/3091597/EFI.zip)

**Comment by andreimerfu** [comment]
Morning,

I try using your files but not work. 😢 The problem is the same. Something related to Intel Graphics.
![photo_2019-04-18_08-19-10](https://user-images.githubusercontent.com/12085472/56338594-508d7980-61b3-11e9-96e0-148b85954bb4.jpg)

My Asus model name is: Rog GL552VW-CN117H

**Comment by Qunqun64** [comment]
Morning.

I can't read the attachment, picture is too blurring...
Have you a black screen after this moment ?
Or the screen remains block into this page ?
An idea for check if the pc crashed, is to put a mouse and check the light. If she is lit, the PC perhaps works.

Before I try with 12go RAM, because I upgraded this, but it can't work, so I decided to put 8go, not 12. And it resolved many problems.
Maybe have you 2 sticks of ram ?

Let me know. (And pardon my bad English, I'm French, ;) )

**Comment by andreimerfu** [comment]
No i have just 1 stick with 16gb and after that screen, i get the message 'Please go to https://panic.apple.comto report this panic'

**Comment by Qunqun64** [comment]
in clover connfigurator, check : 
boot :
	darkwake 1
	nv_disable=1
device :
	0x0000 in all cases in fake id
graphics :
	inject intel
rt Variables :
	rom : usemacaddr0
	csractiveconfig : 0x67
smbios :
	memory, add memory, you are in single channel, write slot, size, frequency, vendor, and type.
system parameters :
	generate new custom uuid

in asus bios, check : 
secure boot, fast boot disable
vd-t, Intel Virtualization Technology, enable, (this is not useful)
graphics memory : 128Mo or fast.

when you start clover, activate "debug kexts" with pressing the spacebar.

if it doesn't work, I don't know.

**Comment by andreimerfu** [comment]
Hi.

Thank you @Qunqun64, it works now!
But my M.2 SSD drive doesn't appear in disk utility just my NTFS 2TB Hard Drive. My SSD is formatted in Ext4 (Ubuntu). 

Edit: Sorry my fault. The SSD works. I've formatted a partition in Mac OS Extended Journaled but in the installer, I've got the message ' This disk cannot be used to start up your computer'. Maybe is necessary to format my SSD in one partition without Ubuntu?

Edit 2: I formatted my partition in APFS and now works. I'm waiting... 

Edit 3: It works! With few problems, but it works!. My laptop display is black, it works just using an HDMI cable and my Wi-FI card is Intel. 😢

**Comment by Qunqun64** [comment]
Cool ! It's good !

For me, it works now, before I erased my disk to osx journaled, but it's bad.
So I erased to apfs, ant it works! (Thanks for idea!)

I have a Mojave desktop. But I didn't understand what is the work in "macos Mojave post-installation ? Where put I the kexts files ? What must I do ?

I think for your problems, @andreimerfu, this tab, post-installation, resolve many problems, but I didn't understand what make this...

**Comment by andreimerfu** [comment]
After installation, you should create another EFI partition to the <Your_Macintosh_Disk> with the same config like pre-installation. After that copy kext and driver64 folders and config.plist (not preinstall) from the repository to EFI. And it works all for me except Bluetooth and Intel WiFi. For me is enough, I will revert to Ubuntu :) Thank you very much for your support @Qunqun64

**Comment by Qunqun64** [comment]
Hello.

I followed your instructions, (create new efi partition, and copy paste kexts and driver's,) but I still have problems: keyboard backlight, Bluetooth, battery works, but sleep, screen backlight, track pad, USB 3.0, and wifi don't works. For wifi I think it's impossible to make anything, @fidele007 say it's impossible, but for the rest, I didn't understand why it doesn't work.
I was trying with the config.plist not preinstall, but I can't start macos with this: my PC goes out immediately after clover choices.

Can you help me? Have you an idea? Should I do anything about the DSDT files?

Thank you for your help @andreimerfu, and good return to Ubuntu!

EDIT: I solved the usb problem, modifying the ssdt-usb file, but I can't read the other ssdt files to do the same thing: I see illegible characters on textedit...

**Comment by Qunqun64** [comment]
Hello.

I come with new!
I do not understand anything anymore. with a lot of work, I try to run the sound and display, but I can't: the sound worked, but even without any manipulation, it does not work, and can't run the backlight of the screen: I am stuck in max luminosity
Moreover, usb ports no longer work ...
I managed to run the trackpad, thanks to the @baobaoit script in another thread. thanks to him.

But for the rest I need help: I ​​searched everywhere, but it goes beyond my skills.

Thank you in advance for any help on these 3 points: backlight of the screen, sound, and usb.

Have a good evening!

**Comment by baobaoit** [comment]
Would you mind upload your Clover folder after you extract the DSDT (at clover boot management, press F4 button before you boot into macOS). I will try to help you with your problems when I have time.

**Comment by Qunqun64** [comment]
Thank a lot, I see you make a very good job in others thread, I hope you can help me!
My clover folder, I hope it isn't too destroyed after lot of manipulations! [CLOVER.zip](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/files/3114030/CLOVER.zip)

good night and thank you in advance!

**Comment by baobaoit** [comment]
I had done with your CLOVER. You can try and tell me if it work or not. I'm busy with my work now, so when I have time, I will help anybody that face with problem here. (with my knowledge)
[CLOVER.zip](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/files/3117472/CLOVER.zip)

**Comment by Qunqun64** [comment]
Thank you very much for what you did, everything works perfectly!
Thank you very much for the time you spent there!
I could observe some bugs anyway: I can't put the computer to sleep, because it does not wake up properly: the mouse only works, the rest of the screen is black.
The sd card port does not work, but it does not matter because I don't use it.
And finally, you can disable the trackpad with the button impécrsyst, but not with the fn + f9, dedicated button ... is it possible to change that? How to do it ?

And finally, is it possible to explain to me how you proceeded to solve my problems, if you have the time? It will allow me to learn and solve problems afterwards!

Thank you in advance, and good evening!

**Comment by baobaoit** [comment]
Dear @Qunqun64, I have read your comment, and I will explain with you something.

About to put computer to sleep, I think that you need to patch for disable dGPU (the graphic card GTX), because I don't remember how to patch it. You can read [here](https://www.insanelymac.com/forum/topic/295584-disabling-nvidia-optimus-card-on-all-laptops/) and the instruction [here](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/wiki/Native-power-management-%28Proper-sleep-wake%29)

For disable trackpad, I heard someone told that "you press the "prt sc sysrq" for disable the trackpad". I don't know how to change, and I don't care about it.

Before you apply any patch, you must apply the patch `[syn] Rename _DSM  methods to XDSM`
Then I just patch the DSDT following the instruction at [Wiki](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/wiki/DSDT-SSDT-patches) and [patch VoodooI2C](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/wiki/TouchPad-with-VoodooI2C)

About patch VoodooI2C, beside 3 patch is available in MaciASL, you need to replace the content of Scope (_SB.PCI0.I2C1)
```
Scope (_SB.PCI0.I2C1)
{
    Device (ETPD)
    {
        Name (SBFB, ResourceTemplate ()
        {
            I2cSerialBusV2 (0x004C, ControllerInitiated, 0x00061A80,
                AddressingMode7Bit, "\\_SB.PCI0.I2C1",
                0x00, ResourceConsumer, _Y34, Exclusive,
                )
        })
        Name (SBFI, ResourceTemplate ()
        {
            Interrupt (ResourceConsumer, Level, ActiveHigh, Exclusive, ,, )
            {
                0x0000005F,
            }
        })
...
```

With those content, before the Scope (_SB), this content I had found on another successful patch DSDT for Asus laptop of a guy.
```
Scope (_SB.PCI0.I2C1)
    {
        Device (ETPD)
        {
            Name (SBFG, ResourceTemplate ()
            {
                GpioInt (Level, ActiveLow, ExclusiveAndWake, PullDefault, 0x0000,
                    "\\_SB.PCI0.GPI0", 0x00, ResourceConsumer, ,
                    )
                    {   // Pin list
                        0x0047
                    }
            })
            Name (SBFB, ResourceTemplate ()
            {
                I2cSerialBusV2 (0x004C, ControllerInitiated, 0x00061A80,
                    AddressingMode7Bit, "\\_SB.PCI0.I2C1",
                    0x00, ResourceConsumer, _Y33, Exclusive,
                    )
            })
            CreateWordField (SBFB, \_SB.PCI0.I2C1.ETPD._Y33._ADR, BADR)  // _ADR: Address
            Name (_ADR, One)  // _ADR: Address
            Method (_HID, 0, NotSerialized)  // _HID: Hardware ID
            {
                If (ELAN)
                {
                    Store (0x15, BADR)
                    Return ("ELAN1000")
                }

                Return ("ELAN1000")
            }

            Name (_CID, "PNP0C50")  // _CID: Compatible ID
            Name (_UID, One)  // _UID: Unique ID
            Name (_S0W, 0x03)  // _S0W: S0 Device Wake State
            Method (_S3W, 0, NotSerialized)  // _S3W: S3 Device Wake State
            {
                If (LEqual (S0ID, Zero))
                {
                    Return (0x03)
                }
                Else
                {
                    Return (Zero)
                }
            }

            Method (_DSM, 4, NotSerialized)  // _DSM: Device-Specific Method
            {
                If (LEqual (Arg0, ToUUID ("3cdff6f7-4267-4555-ad05-b30a3d8938de") /* HID I2C Device */))
                {
                    If (LEqual (Arg2, Zero))
                    {
                        If (LEqual (Arg1, One))
                        {
                            Return (Buffer (One)
                            {
                                 0x03                                           
                            })
                        }
                        Else
                        {
                            Return (Buffer (One)
                            {
                                 0x00                                           
                            })
                        }
                    }

                    If (LEqual (Arg2, One))
                    {
                        Return (One)
                    }
                }
                Else
                {
                    Return (Buffer (One)
                    {
                         0x00                                           
                    })
                }
            }

            Method (_STA, 0, NotSerialized)  // _STA: Status
            {
                If (LEqual (TPIF, Zero))
                {
                    Return (Zero)
                }

                If (And (DSYN, One))
                {
                    Return (Zero)
                }

                Return (0x0F)
            }

            Method (_CRS, 0, NotSerialized)  // _CRS: Current Resource Settings
            {
                Return (ConcatenateResTemplate (SBFB, SBFG))
            }
        }
    }
```

About the config.plist, I had added two patch in Kernel and Kext patches > KextsToPatch (you can search on Google about those patch)
1. Prevent Apple I2C kexts from attaching to I2C controllers, credit CoolStar
2. Prevent AppleGFXHDA.kext from attaching to audio device

English is not my primary language, so I hope you can understand what I'am saying.

**Comment by Qunqun64** [comment]
I thank you for these explanations, I understand that we must really know if we want to get things done. Otherwise, we must recover in those who know how to do.

And I also thought that in the KextsToPatch, you had to add links, not prevent macos from creating them badly! :)

Thank you for allowing me to mount a hackintosh correct and functional, I pass the subject solved;)

Good continuation !

**Comment by ohua28** [comment]
> I had done with your CLOVER. You can try and tell me if it work or not. I'm busy with my work now, so when I have time, I will help anybody that face with problem here. (with my knowledge)
> [CLOVER.zip](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/files/3117472/CLOVER.zip)

can you fix mine? i used this one but not bluetooth and wifi but the trackpad works here

**Comment by baobaoit** [comment]
> > I had done with your CLOVER. You can try and tell me if it work or not. I'm busy with my work now, so when I have time, I will help anybody that face with problem here. (with my knowledge)
> > [CLOVER.zip](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/files/3117472/CLOVER.zip)
> 
> can you fix mine? i used this one but not bluetooth and wifi but the trackpad works here

You need to replace your wifi card with bcm94352z (dw1560). Because intel’s wifi card is not working with macOS.

Did you read [this](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/wiki/Wi-Fi-and-Bluetooth-with-BCM94352Z)?

**Comment by ohua28** [comment]
> > > I had done with your CLOVER. You can try and tell me if it work or not. I'm busy with my work now, so when I have time, I will help anybody that face with problem here. (with my knowledge)
> > > [CLOVER.zip](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/files/3117472/CLOVER.zip)
> > 
> > 
> > can you fix mine? i used this one but not bluetooth and wifi but the trackpad works here
> 
> You need to replace your wifi card with bcm94352z (dw1560). Because intel’s wifi card is not working with macOS.
> 
> Did you read [this](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/wiki/Wi-Fi-and-Bluetooth-with-BCM94352Z)?

i have the supported wifi card im using your config2 but the problem is bluetooth and how to make that config as primary config
