### ISSUE TITLE
Black screen with a blinking cursor

### ISSUE THREAD

**Issue by f159752** [fidele007/Asus-ROG-GL552VW-Hackintosh#15]
I'm trying to install mojave on my laptop.
After installing mojave with Unibeast, I replace CLOVER and BOOT folders.
I boot from the flash drive and see a black screen with a blinking cursor.
What am I doing wrong?
Did anyone have this?
Does the version of the operating system matter? Because I tried 14.0.6 and 14.0.5

**Comment by baobaoit** [comment]
Please following this [guide](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/wiki/Install-macOS-Moajve), don't using UniBeast because it using for desktop.
