### ISSUE TITLE
Display Brightness

### ISSUE THREAD

**Issue by intelect** [fidele007/Asus-ROG-GL552VW-Hackintosh#2]
Hello, I am have some issue with being able to adjust my display brightness. I have done all f the patches I have seen to do.

**Comment by fidele007** [comment]
Take a look at [this guide](https://www.tonymacx86.com/threads/guide-patching-dsdt-ssdt-for-laptop-backlight-control.152659/). If you're on Mojave, you can follow my [specific guide](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/wiki/DSDT-SSDT-patches#ssdts) for ASUS ROG GL552VW
