### ISSUE TITLE
Keyboard backlight not working

### ISSUE THREAD

**Issue by baobaoit** [fidele007/Asus-ROG-GL552VW-Hackintosh#3]
Dear @fidele007 , I has patched DSDT with KeyboardBacklight16, but my backlight was not working.
Is there any settings else that you not write?

**Comment by fidele007** [comment]
Make sure that you also have AsusNBFnKeys kext installed. The latest version as of now is v2.6 (https://osxlatitude.com/forums/topic/1968-fn-hotkey-and-als-sensor-driver-for-asus-notebooks/).

**Comment by baobaoit** [comment]
I used the AsusNBFnKeys in your CKO folder. I'll try download from your link. Also, I need installe it to LE or CKO? Thank you!

**Comment by baobaoit** [comment]
Hello @fidele007 , I had installed the lastest AsusNBFnKeys + Lilu kext, and patched DSDT with your patch suggest. Then I reboot my laptop. When it boot up, the keyboard backlight still not working. I have try using Fn+F3/4 but nothing happend. I'm using Asus GL552VW like this tutorial with macOS Mojave installed. Can you suggest for me any idea?

**Comment by baobaoit** [comment]
I had solved via a hard research! With those code below was made my keyboard backlight to worked. Can you update to your wiki? And modified the KeyboardBacklight16 patch.

UPDATE 1: this is patch 4 level, if you want to use patch 16 level just replace `Store (DerefOf (Index (PWKB, Local0)), Local1)` With `Store (DerefOf (Index (KBPW, Local0)), Local1)` or if you don’t have `Name (KBPW...` so you can change the content of `Name (PWKB...` from `0x00, 0x55, 0xAA, 0xFF` to `0x00, 0x11, 0x22, 0x33, 0x44, 0x55, 0x66, 0x77, 0x88, 0x99, 0xAA, 0xBB, 0xCC, 0xDD, 0xEE, 0xFF`

```c#
            Name (PWKB, Buffer (0x04)
            {
                 0x00, 0x55, 0xAA, 0xFF                         
            })
            Name (BOFF, Zero)
            Method (SKBL, 1, NotSerialized)
            {
                If (Or (LEqual (Arg0, 0xED), LEqual (Arg0, 0xFD)))
                {
                    If (And (LEqual (Arg0, 0xED), LEqual (BOFF, 0xEA)))
                    {
                        Store (Zero, Local0)
                        Store (Arg0, BOFF)
                    }
                    ElseIf (And (LEqual (Arg0, 0xFD), LEqual (BOFF, 0xFA)))
                    {
                        Store (Zero, Local0)
                        Store (Arg0, BOFF)
                    }
                    Else
                    {
                        Return (BOFF)
                    }
                }
                ElseIf (Or (LEqual (Arg0, 0xEA), LEqual (Arg0, 0xFA)))
                {
                    Store (KBLV, Local0)
                    Store (Arg0, BOFF)
                }
                Else
                {
                    Store (Arg0, Local0)
                    Store (Arg0, KBLV)
                }

                Store (DerefOf (Index (PWKB, Local0)), Local1)
                ^^PCI0.LPCB.EC0.WRAM (0x04B1, Local1)
                ^^PCI0.LPCB.EC0.WRAM (0x044B, Local1)
                Return (Local0)
            }

            Method (GKBL, 1, NotSerialized)
            {
                If (LEqual (Arg0, 0xFF))
                {
                    Return (BOFF)
                }

                Return (KBLV)
            }
```

**Comment by fidele007** [comment]
Updated the guide. After double checking, it seems like I used a different patch and not the KeyboardBacklight16 one. I didn't include the following patch since it's already included in the original DSDT:

```txt
Name (PWKB, Buffer (0x04)
            {
                 0x00, 0x55, 0xAA, 0xFF                         
            })
```

Thanks for your contribution 👍

**Comment by rbc33** [comment]
hi, i installed all the kext but I cat get my backlight working, also I can't find the parameters SBFB and SBFI for patching my touchpad 
[DSDT.aml.zip](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/files/2812694/DSDT.aml.zip)

**Comment by baobaoit** [comment]
Did you mean keyboard backlight or display backlight?

**Comment by baobaoit** [comment]
SSDT-PNLF.aml and AppleBacklightFixup.kext for brightness patch according to RehabMan's guide.

If about display backlight, you should put AppleBacklightFixup in /Library/Extensions and SSDT-PNLF in /EFI/CLOVER/ACPI/patches then you put the name SSDT-PNLF.aml in config.plist by Clover Configurations at SortedOrder

**Comment by baobaoit** [comment]
By the way, when you put kext in /Library/Extensions, you must remember run 
sudo kextcache -i / 
on Terminal.

**Comment by rbc33** [comment]
@baobaoit my system crushed and the acpi you patched for mi doesn't works anymore, would you mind to repatch it?it would be a huge favor

pd: im working to learn how to do it by myself

[CLOVER.zip](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/files/2866577/CLOVER.zip)

**Comment by baobaoit** [comment]
Are you re-extract your DSDT via press F4 before you boot up Mac?

**Comment by rbc33** [comment]
yes I did anyway I did it again to be sure
[CLOVER.zip](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/files/2870947/CLOVER.zip)

**Comment by rbc33** [comment]
this its what I get when I try to boot with the clover you patched 
![img_20190215_214051](https://user-images.githubusercontent.com/28944425/52883948-e3d31000-316c-11e9-9f72-059766db91b8.jpg)

**Comment by baobaoit** [comment]
Did you set DVMT from 32 to 64?

**Comment by rbc33** [comment]
Yes, I did everything but the boot crushed and I can't use that ACPI/patched no longer,

**Comment by baobaoit** [comment]
I think you should re-install macOS then put my patched again.

**Comment by rbc33** [comment]
That is what I did but it doesn't works the boot crushes with the message I took the picture

**Comment by rbc33** [comment]
@baobaoit so I finally resolved it, I didn't save my bios configuration when I changed DVMT...(facepalm)
right click still doesn't work but at this point it's not so important and I learn how to modify my DSDT in the meanwhile

thank you very much for your support

**Comment by baobaoit** [comment]
So this is a good news. I’m feeling great when heard you say that. It’s my pleasure.

**Comment by rbc33** [comment]
It's all thanks to you

**Comment by ramandika** [comment]
I try to patch keyboard back light but this errors show up when trying to patch @baobaoit 
![image](https://user-images.githubusercontent.com/7370645/93110750-efd3da80-f6df-11ea-965c-a334fab2933a.png)

Any ideas on it?
