### ISSUE TITLE
Dualboot tutorial

### ISSUE THREAD

**Issue by Gentle888** [fidele007/Asus-ROG-GL552VW-Hackintosh#4]
Yes, this can be critical in some cases. There is plenty of people, who don't know about that.

**Comment by fidele007** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Write guide for dual-booting hackintosh with other OSes](https://trello.com/c/4flPJCCc/43-write-guide-for-dual-booting-hackintosh-with-other-oses)

**Comment by fidele007** [comment]
Guide is up: https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/wiki/Dual-Booting-Hackintosh-with-other-Operating-Systems
