### ISSUE TITLE
Did you mean keyboard backlight or display backlight?

### ISSUE THREAD

**Issue by rbc33** [fidele007/Asus-ROG-GL552VW-Hackintosh#5]
Did you mean keyboard backlight or display backlight?

_Originally posted by @baobaoit in https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/issues/3#issuecomment-458943208_

 it's the keyboard backlight

**Comment by baobaoit** [comment]
About keyboard backlight you can follow the tutorial at Wiki part. It was updated following my post. It needed AsusNBFnKeys.kext be installed in LE and patch DSDT.

**Comment by rbc33** [comment]
actually the display backlight doesn't works neither and when I try to patch my DSDT it's always different the why I upload it, this its very frustrating I've been working on it for 2 or 3 weeks

**Comment by baobaoit** [comment]
Can you upload the  /EFI/CLOVER so I will try to patch some common problems and backlight for you, on tomorrow.

**Comment by rbc33** [comment]
I've tried patching but any file I put in patched carpet makes the boot crush
[CLOVER.zip](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/files/2813061/CLOVER.zip)

**Comment by rbc33** [comment]
thanks for taking your time to help

**Comment by rbc33** [comment]
P.D my touchpad device name it's \_SB.PCI0.I2C1.ETPD

**Comment by baobaoit** [comment]
Here you are! I had patched for you (except patch disable GPU NVIDIA).
[CLOVER_patched_DSDT_20190131.zip](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/files/2815665/CLOVER_patched_DSDT_20190131.zip)

**Comment by rbc33** [comment]
THANKS!! the touchpad it's still not working but everything else works!!

**Comment by baobaoit** [comment]
You can try to copy 2 kexts: VoodooI2C and VoodooI2CELAN from Clover/kexts/other to LE then open terminal and run 3 lines command below (each line you must enter before the next command)
`sudo chmod -R 755 /Library/Extensions`
`sudo chown -R root:wheel /Library/Extensions`
`sudo kextcache -i /`
Then you reboot your laptop.

**Comment by rbc33** [comment]
it work perfectly!!!!! thanks you very much

**Comment by rbc33** [comment]
hi @baobaoit i made a script to install kali linux optimus and cuda drivers, would you mind to have a look?

**Comment by baobaoit** [comment]
Is it working now?

**Comment by baobaoit** [comment]
Sorry but I don’t use Kali.

**Comment by rbc33** [comment]
yes it works what a piti i think it could work with debian changing the
repositories
