### ISSUE TITLE
right click or two finger click doesn't works

### ISSUE THREAD

**Issue by rbc33** [fidele007/Asus-ROG-GL552VW-Hackintosh#6]

**Comment by baobaoit** [comment]
It's working perfectly for me. You can setting in Settings > Trackpad. Check if Secondary click be ticked.

**Comment by rbc33** [comment]
not for me I've tried two fingersand right click but neither works

**Comment by baobaoit** [comment]
Are you checking in Settings? Take a screenshot (Settings > Trackpad) and upload to your comment, please!

**Comment by rbc33** [comment]
![screenshot 2019-02-01 at 09 45 31](https://user-images.githubusercontent.com/28944425/52112201-1f66c980-2606-11e9-8a35-269e3a5e17b5.png)

**Comment by baobaoit** [comment]
This is my settings and it's working for my laptop. I use 2 fingers tap for secondary click.
![screen shot 2019-02-01 at 3 47 08 pm](https://user-images.githubusercontent.com/31947091/52112335-c19fa500-2638-11e9-81b0-93ef6e6f5174.png)

**Comment by rbc33** [comment]
I've tried it too but seems that no one works

**Comment by baobaoit** [comment]
Hm, I'm sorry but I don't know what is missing. So, I hope @fidele007 can figure out.

**Comment by rbc33** [comment]
thanks @baobaoit, you have been very helpful

**Comment by rbc33** [comment]
so I realised that it works with ctrl + click

**Comment by baobaoit** [comment]
I’m happy when hear that news from you. But so strange.

**Comment by rbc33** [comment]
hi @fidele007 can you help me?
