### ISSUE TITLE
Touchpad doesn't work

### ISSUE THREAD

**Issue by Kl4tch** [fidele007/Asus-ROG-GL552VW-Hackintosh#7]
Hi, I'm new user of Hackintosh. Thanks for this great work, but my system doesn't boot with VoodooI2C.kext.

So, if I exclude VoodooI2C.kext - everything is OK, but touchpad doesn't work

Can you help me please, how can I fix it? 

When I boot with your CLOVER without changes:
![image](https://user-images.githubusercontent.com/22257594/53299550-bc570400-384c-11e9-8124-72eb1d0eaf86.png)

TouchPad in IOService (if I doesn't use DSDT.aml patch) : 
![2019-02-24 14 40 05](https://user-images.githubusercontent.com/22257594/53299566-ec060c00-384c-11e9-9201-be1e95f955fe.png)

How does it recognize in Win:
![image](https://user-images.githubusercontent.com/22257594/53299569-f88a6480-384c-11e9-880c-521ccbea9634.png)

**Comment by baobaoit** [comment]
Did you use I2C and I2CELAN?
Did you patched your dsdt?
If you use the dsdt of this repo, then you need to setup your bios like the requirements in Wiki page.

**Comment by baobaoit** [comment]
And you need these patches in config - kext to patch

```
<dict>
				<key>Comment</key>
				<string>Prevent Apple I2C kexts from attaching to I2C controllers, credit CoolStar</string>
				<key>Name</key>
				<string>com.apple.driver.AppleIntelLpssI2C</string>
				<key>Find</key>
				<data>SU9LaXQ=</data>
				<key>Replace</key>
				<data>SU9LaXM=</data>
				<key>InfoPlistPatch</key>
				<true/>
			</dict>
			<dict>
				<key>Comment</key>
				<string>Prevent Apple I2C kexts from attaching to I2C controllers, credit CoolStar</string>
				<key>Name</key>
				<string>com.apple.driver.AppleIntelLpssI2CController</string>
				<key>Find</key>
				<data>SU9LaXQ=</data>
				<key>Replace</key>
				<data>SU9LaXM=</data>
				<key>InfoPlistPatch</key>
				<true/>
			</dict>
```

**Comment by Kl4tch** [comment]
> And you need these patches in config - kext to patch
> 
> ```
> <dict>
> 				<key>Comment</key>
> 				<string>Prevent Apple I2C kexts from attaching to I2C controllers, credit CoolStar</string>
> 				<key>Name</key>
> 				<string>com.apple.driver.AppleIntelLpssI2C</string>
> 				<key>Find</key>
> 				<data>SU9LaXQ=</data>
> 				<key>Replace</key>
> 				<data>SU9LaXM=</data>
> 				<key>InfoPlistPatch</key>
> 				<true/>
> 			</dict>
> 			<dict>
> 				<key>Comment</key>
> 				<string>Prevent Apple I2C kexts from attaching to I2C controllers, credit CoolStar</string>
> 				<key>Name</key>
> 				<string>com.apple.driver.AppleIntelLpssI2CController</string>
> 				<key>Find</key>
> 				<data>SU9LaXQ=</data>
> 				<key>Replace</key>
> 				<data>SU9LaXM=</data>
> 				<key>InfoPlistPatch</key>
> 				<true/>
> 			</dict>
> ```

Thanks for fast reply and helping

All folder CLOVER I use from this rep, without any changes. I add your patches but it still doesn't work (panic still, again with VoodooGPIO.kext ). What should I do?

BIOS is seted as in rep.

**Comment by baobaoit** [comment]
Did you use branch mojave? I think you should re-extract your dsdt then you patch it by yourself.

**Comment by Kl4tch** [comment]
I use mojave branch.
Thanks for helping. Yes, you was right, patches in config (kext to patch) helped me and system boot successful, but touchpad doesn't work still. I used your guide to rbc33 (LE folders + 3 commands) but still it doesn't work.
I get clean DSDT, but it have some errors:
![image](https://user-images.githubusercontent.com/22257594/53328409-eff06780-38fa-11e9-836a-4309b5ceb324.png)
Can you help me with this?

So, now I have all folder CLOVER from this rep + 2 your kexts patches. Only touchpad and Mic doesn't work (I saw separate guide with Mic, but Touchpad is must have now, I try run it 2 days).
These files I get from CLOVER:
[origin.zip](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/files/2899843/origin.zip)

**Comment by rbc33** [comment]
Try to use the clover folder with the dsdt that @baobaoit patched for me? And don't forget to change the dvmt at bios, then install all the kext

**Comment by baobaoit** [comment]
Here is your DSDT that I had patched - except `Disabling discrete graphics card`. You need to put this file in your /EFI/CLOVER/ACPI/patched/ then shutdown and turn on again.
[DSDT.zip](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/files/2899991/DSDT.zip)

**Comment by baobaoit** [comment]
I forgotten to told with you about these thing in the last commented. That is you should use `Terminal` for copy those kexts - not using your Command (Alt) + C then Command + V to your LE or using Right click then Copy and Paste. These lines is for copy kext(s) to your LE.
`sudo cp -R <you can drag your kext(s) to Terminal> /Library/Extensions`
Or you can read this article: https://www.tonymacx86.com/threads/268964/

**Comment by Kl4tch** [comment]
![image](https://user-images.githubusercontent.com/22257594/53331055-0f8a8e80-3901-11e9-9821-9c0099ccbaab.png)
Thanks, man. Works great with your DSDT.

**Comment by Fabio24Silva** [comment]
Hi guys, I'm with the same problem as Author, I'm quite new on this, and finally were able to install macOS, my problem is that I didn't understand what the author did to boot with the VoodooI2C.kext even before he installed the DSDT from @baobaoit. I only have my clover on EFI folder just like this repo, nothing more, still don't get what I need to do to patch some kext and from the link @baobaoit shared it looks like the kexts should be in /Library/Extensions but what kexts? Every kext from this repo should be there? And on clover it should be empty? I know maybe some of those question are a bit stupid but I would appreciate some help. Thanks in advance!

**Comment by baobaoit** [comment]
All the kexts that necessary for you. For me is all kexts except kexts of Brcm because I didn’t have replacement wifi card.

**Comment by Fabio24Silva** [comment]
I have all the kexts on clover, but right now I can only boot if I remove VoodooI2C.kext from Clover, what should I do to correct this? Should I add some patch that is not on this repo? If so, how can I add the patch? Via clover? Sorry for making so many question, it's my first time doing this.

**Comment by baobaoit** [comment]
Try this in Kext and kernel patch > KextToPatch https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/issues/7#issuecomment-466788113

**Comment by Fabio24Silva** [comment]
![captura de ecra 2019-03-05 as 01 14 24](https://user-images.githubusercontent.com/28763038/53773908-312cdc80-3ee4-11e9-9724-5d071e123c25.png)

Well, I think I've patched it as it should be, I patched the file config.plist on editor, added again VoodooI2C.kext but I get the error again, I even added your DSDT to ACPI/patched on clover but it doesn't boot, any idea?

**Comment by baobaoit** [comment]
I think you should try to delete the DSDT in ACPI/patched. If it can boot, you can post your origin ACPI for me, I will patch it on my free time.

**Comment by Fabio24Silva** [comment]
Well it is now booting but deleting DSDT was not enough, I had to delete every file on ACPI/patched to get it too boot

**Comment by baobaoit** [comment]
Ok so when you boot to clover-manager-boot-screen. Press the F4 button. Then boot to your mac. And upload your origin via drag it to the comment-text-box.

**Comment by Fabio24Silva** [comment]
[origin.zip](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/files/2928930/origin.zip)

Here they are, thanks for your help!

**Comment by baobaoit** [comment]
This is for you @Fabio24Silva - like another, I didn't patch `Disabling discrete graphics card`.

[DSDT.zip](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/files/2930616/DSDT.zip)

**Comment by Fabio24Silva** [comment]
Man i really appreciate your help, it's now working! Thanks man!!
Just one more question, I will now install kexts on /Library/Extensions, should I leave them too on Clover or I delete them from clover and install them all on /Library/Extensions ?

**Comment by baobaoit** [comment]
Nice to hear your good news.

First, you need to read again my comment above here https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/issues/7#issuecomment-466958505

The finally, you should install kexts on /Library/Extensions, all your kexts but except kexts about Brmc, if you don’t replacement your wifi card. Then you can leave those kexts on Clover, do not need to delete them.

**Comment by Fabio24Silva** [comment]
Yes I've done it already, mouse is working but two buttons or right click option don't do anything, scroll and left button work well, is it supposed to be like this? And keyboard light is working well but I can't control luminosity with the fn option, is it normal too?

**Comment by baobaoit** [comment]
About the mouse, you can try any settings on settings > trackpad.
I still can control the keyboard backlight with the fn like Windows. It has 4-levels about backlight.

**Comment by Fabio24Silva** [comment]
Yeah i've got the mouse working now, one strange thing that is not such a big deal is that I can't select files with the touchpad like I left click but the mouse freezes, and yes the keyboard works well with me too. I was talking about the fn + brightness +/- on the screen. That one isn't working with me

**Comment by baobaoit** [comment]
Great to hear. But I think that I can’t help you the other problems. With me, it’s working flawlessly. You can try to shut down and turn on again. And about the screen brightness you need to put back the SSDT to the patched folder. Then check the config.plist is have it on ordered list at the bottom right. You click + and filled those name. There are 2 SSDT on this repo.

**Comment by Fabio24Silva** [comment]
Well I have the mouse working fine now, but the brightness keeps not working, I've the 2 SSDT working on the clover, can you please explain me how config.plist should be for this to work?
My patches:
![captura de ecra 2019-03-05 as 12 27 13](https://user-images.githubusercontent.com/28763038/53805464-1b4e0480-3f42-11e9-8643-734afdc28e07.png)
![captura de ecra 2019-03-05 as 12 27 29](https://user-images.githubusercontent.com/28763038/53805474-22751280-3f42-11e9-9846-7d7c306bffde.png)

**Comment by baobaoit** [comment]
You can send me your CLOVER folder. I will check it for you.

**Comment by Fabio24Silva** [comment]
[CLOVER.zip](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/files/2930890/CLOVER.zip)
I would really appreciate, thanks!

**Comment by baobaoit** [comment]
[CLOVER.zip](https://github.com/fidele007/Asus-ROG-GL552VW-Hackintosh/files/2930926/CLOVER.zip)
Here you are!

**Comment by Fabio24Silva** [comment]
Thanks man, but I tried it right now and it is still with the same problem, all the keys work well even keyboard backlight but screen brightness doesn't work

**Comment by baobaoit** [comment]
You can go to the Tonymacx86 forum. I don’t know what to help you now. I had did all I knew.

**Comment by Fabio24Silva** [comment]
Man, I just changed the keys for birghtness and it works so no big deal. Thanks man for all your help, my hackintosh is working pretty well!

**Comment by baobaoit** [comment]
You are welcome!
